repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$|__init__.py
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Black
  - repo: local
    hooks:
      - id: system
        name: Unit Tests
        entry: poetry run pytest tests -v
        pass_filenames: false
        language: system
