[tool.poetry]
name = "walnut"
version = "0.1.0"
description = "Tiny library to create daily tooling"
authors = ["Esteban del Boca <esteban.delboca@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.2"
chevron = "^0.14.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
